User nobody
Group nogroup
Port 8888
Timeout 600
MaxClients 20

FilterExtended On
FilterURLs Off
FilterDefaultDeny Yes
Filter "/etc/tinyproxy/filter"

Allow 127.0.0.1
Allow 172.16.0.0/12

LogLevel Connect
